[Refactor/#171] convention refactor
Team-UniVoice/UniVoice_iOS pull request #173
Opened 2024-08-10 11:41 UTC by oyslucy

## 📌 What is the PR?
- git convention에 따라 리팩토링 합니다

## 🪄 Changes
-  파일 네이밍 체크
-  final, 접근 제한자 체크
-  SwiftLint 체크
-  개행 컨벤션 체크
-  VC, View 컨벤션 체크

## 🙆🏻 To Reviewers
- 기존 MainHomeModel에 있던 QuickScanProfile, Notice Model을 다른 파일로 분리해주었습니다.
- AffiliationType enum도 다른 파일로 분리해주었습니다.
- article라고 적힌 모든 것들을 notice로 몽땅 바꿨습니다.
- 컨벤션 안지켜서 죄송합니다 고치면서 반성했어요~

## 💭 Related Issues

- Resolved: #171

2024-08-10 11:57 UTC, kingjeongkong approved these changes
고생하셨네요
처음에 네이밍을 Notice가 아니라 Article로 하신 이유가 뭘까요?

2024-08-10 11:57 UTC, kingjeongkong commented on UniVoice/UniVoice/Presentation/DetailNotice/View/DetailNoticeView.swift
> -
해당 코드는 사용 안해서 삭제하신건가요?

2024-08-10 12:04 UTC, FpRaArNkK requested changes
고생많으셨습니다! 필요 부분들에 잘 작성해주신 것 같은데,
NoticeCVC의 preview코드 삭제만 진행해주시고, 다시 push 부탁드립니다!

2024-08-10 12:04 UTC, FpRaArNkK commented on UniVoice/UniVoice/Presentation/MainHome/View/Cell/QuickScanCollectionViewCell.swift
> +        circleView.addSubview(noticeNumber)
superView에서 다시 subView로 추가하는 이유가 있을까요?

2024-08-10 12:04 UTC, FpRaArNkK commented on UniVoice/UniVoice/Presentation/MainHome/ViewModel/MainHomeViewModel.swift
>      }
DTO - Model mapping 코드는 DTO 단에서 정리해주시면 좋을 것 같습니다!
ViewModel의 역할보다는 DTO로 넘겨주시면 좋을 것 같습니다~
밑에 매핑함수도 DTO로 옮겨주시면 좋을 것 같아요.

2024-08-10 12:06 UTC, oyslucy commented
> 고생하셨네요 처음에 네이밍을 Notice가 아니라 Article로 하신 이유가 뭘까요?

개발 시작 전에 다같이 정했던 Notice라는 네이밍을 인지하지 못하고 적었습니다

2024-08-10 12:06 UTC, oyslucy commented on UniVoice/UniVoice/Presentation/DetailNotice/View/DetailNoticeView.swift
> -
다른 파일에도 똑같은 함수가 필요해서 Date extension에 해당 함수를 적었습니다

2024-08-10 12:17 UTC, jaminleee approved these changes

2024-08-10 12:17 UTC, jaminleee commented on UniVoice/UniVoice/Domain/MainHome/QuickScanProfile.swift
> +    let noticeNumber: Int // 읽지 않은 공지 개수
주석 윗줄로 옮겨줘도 좋을 것 같아요!

2024-08-10 12:18 UTC, FpRaArNkK approved these changes
수정 사항 확인했습니다! 고생하셨습니다 👍

2024-08-10 12:39 UTC, merged

2024-08-13 08:25 UTC, oyslucy commented on UniVoice/UniVoice/Presentation/MainHome/View/Cell/QuickScanCollectionViewCell.swift
> +        circleView.addSubview(noticeNumber)
circleView(noticeNumber의 superView)의 크기를 재조정하기 위해 circleView를 삭제하고 다시 위치를 조정하며, noticeNumber도 동시에 삭제 후 위치조정을 해주었습니다