[Feat/#19] Main home UI (~Quick Scan)
Team-UniVoice/UniVoice_iOS pull request #24
Opened 2024-07-08 10:59 UTC by oyslucy

## 📌 What is the PR?
Main Home UI + 비즈니스 로직을 작성하였습니다. 

## 🪄 Changes

- empty View
- Quick Scan UI

## 🌐 Common Changes
- custom UIView
- img

## 📸 Screenshot
<img src = "https://github.com/Team-UniVoice/UniVoice_iOS/assets/84556636/9828c8d8-7c5f-4822-844c-71ef4c5151df" width ="250">|

## 🙆🏻 To Reviewers
MainUI 전부 구현 후에 PR 올리려고 했는데 비즈니스 로직까지 추가하다보니 볼륨이 너무 커질듯 해서 잘라서 올립니다 🥺
**비즈니스 로직 중심**으로 피드백해주시면 감사하겠습니다 !!
- 같은 화면에 collection View 하나와 table View 하나가 더 있어서 data Bind 로직을 cell 안에다가 작성했는데.. 이 방식으로 진행해도 괜찮을까요?
- dummy data를 써서 view model에서 behavior relay가 아닌 init을 썼는데,.. api 연결때도 괜찮을지..
- input 정의.....가 모호해졌다고 생각합니다,,
- (추후에) QuickScanVM과 AnnouncemnetVM을 분리해서 작성해도 될지? 
- (추후에) RxDataSources가 아닌 DiffableDataSource 쓸지? 
               구글링해보니 타겟이 높을 경우엔 DiffableDataSource가 훨 간편하다고 해서
- 갈아엎을 각오돼잇으니 ㅎㅎㅎㅎㅎ... 많은 지적 부탁드림니다ㅏㅏㅏ

## 💭 Related Issues

- Resolved: #19

2024-07-08 12:39 UTC, FpRaArNkK requested changes
너무너무 고생많으셨습니다! 많은 고민의 흔적이 보여서 너무 멋있네요..!
다만 개발 구현 방향과 다른 부분이 보여서 코멘트를 남겨놓았습니다.
이를 참고해주시고, 수정해주시면 감사하겠습니다! 같이 고쳐나가봅시다! 파이팅🔥🔥

2024-07-08 12:39 UTC, FpRaArNkK commented on UniVoice/UniVoice/Global/Resource/Assets.xcassets/mainLogo.imageset/Group 1707481233.png
로고 이미지를 .svg 파일 말고 .png 파일로 등록하신 이유가 있을까요?

2024-07-08 12:39 UTC, FpRaArNkK commented on UniVoice/UniVoice/Global/Resource/Assets.xcassets/emptyImage.imageset/Rectangle 2862019.png
임시로 비워놓은 이미지일까요??

2024-07-08 12:39 UTC, FpRaArNkK commented on UniVoice/UniVoice/Presentation/Components/CustomView.swift
> +        }
퀵스캔 화면의 공지 개수 내용의 경우 라벨의 길이("1", "11", "111")에 따라
캡슐의 형태로 가로가 길어져야합니다! 한 글자일때만 원형입니다!
cornerRadius는 `전체 높이/2`로 가져가시되 너비를 라벨 길이에 따라 동적으로 주시면 구현 가능합니다.

2024-07-08 12:39 UTC, FpRaArNkK commented on UniVoice/UniVoice/Presentation/Components/CustomView.swift
CustomView의 역할이 모호한 것 같아요! 
이름이 모호하다면, 주석 `///`을 달아 어떤 역할을 하는 뷰인지 명확히 해주시면 좋아요!
또한 별개의 UIView로 관리하는 것보다 CollectionView로 관리하는 것이 더 좋아보입니다!

2024-07-08 12:39 UTC, FpRaArNkK commented on UniVoice/UniVoice/Presentation/MainHome/View/Cell/QuickScanCollectionViewCell.swift
> +class QuickScanCollectionViewCell: UICollectionViewCell {
팀 컨벤션 대로 `final class`, `QuickscanCVC`로 변경해주시면 좋을 것 같아요!

2024-07-08 12:39 UTC, FpRaArNkK commented on UniVoice/UniVoice/Presentation/MainHome/View/Cell/QuickScanCollectionViewCell.swift
> +        let input = QuickScanViewModel.Input(trigger: Observable.just(()))
input에 넣을 내용이 없는 경우엔
viewModel에서 input을 빈 struct로 작성하고, Input에 아무것도 안넣으셔도 됩니다!

2024-07-08 12:39 UTC, FpRaArNkK commented on UniVoice/UniVoice/Presentation/MainHome/View/Cell/QuickScanCollectionViewCell.swift
> +extension QuickScanCollectionViewCell {
다만 QuickScanCollectionViewModel의 경우
CollectionViewCell에 연결하는 것는 적절치 않아보여요.
`councilImage, councilName, articleNumber` 를 하나의 Model로 만들어서
`[Model]`로 관리하시고, 이를 CollectionViewCell을 사용하는 View의 ViewModel에서 관리하는게 좋아보입니다!
각 데이터를 가져와 Cell에 바인딩하는 과정, Rx를 사용한 코드는 너무너무 좋습니다! 최고 👍👍

2024-07-08 12:45 UTC, oyslucy commented on UniVoice/UniVoice/Global/Resource/Assets.xcassets/emptyImage.imageset/Rectangle 2862019.png
default 이미지입니다 이름 수정해놓겠습니다 !

2024-07-08 12:45 UTC, oyslucy commented on UniVoice/UniVoice/Global/Resource/Assets.xcassets/mainLogo.imageset/Group 1707481233.png
임시로 넣어놓은 이미지입니다 !

2024-07-08 13:53 UTC, jaminleee approved these changes
고생하셔써용

2024-07-10 13:12 UTC, FpRaArNkK approved these changes
변경 내역 확인했습니다! 고생하셨습니다 🔥🔥

2024-07-10 13:13 UTC, merged